- name: Build and run Docker container locally
  hosts: dockerhost
  become: yes
  vars:
    image_name: nilay2497/abc_tech
    image_tag: "{{ lookup('env','BUILD_NUMBER') | default('latest') }}"
  tasks:
    - name: Build Docker image
      community.general.docker_image:
        build:
          path: /var/lib/jenkins/workspace/MY_CI_JOB/target/
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: no

    - name: Run Docker container
      community.general.docker_container:
        name: abc_tech_container
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
