apiVersion: v1
kind: Service
metadata:
  name: abc-tech-service
  namespace: default   # ✅ add this line
spec:
  selector:
    app: abc-tech
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

