---
- name: Deploy Docker Container
  hosts: local
  tasks:
    - name: Stop existing container
      shell: |
        if [ "$(docker ps -q --filter name=abc_tech_container)" ]; then
          docker stop abc_tech_container
          docker rm abc_tech_container
        fi

    - name: Run new container
      shell: |
        docker run -d --name abc_tech_container -p 9090:8080 nilay2497/abc_tech:{{ build_number }}